spring:
  redis:
    remote: false
    host: 192.168.10.60
    port: 6381
    #password: w5571393#
  rabbitmq:
    host: 47.96.154.183
    port: 5672
    username: admin
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.154.183:3306/springcloudbook?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: w5571393#
  # zipin将采样比例设置为1.0，也就是全部都需要。默认是 0.1
  sleuth:
      sampler:
        probability: 1.0
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: config-server
        enabled: true
      profile: dev
      label: master
    bus:
      enabled: true
      trace:
       enabled: true
hello: hello world!2
feign:
  hystrix:
    enabled: true
management.endpoint.health.show-details: ALWAYS
eureka.instance.leaseRenewalIntervalInSeconds: 30
eureka.instance.health-check-url-path: /actuator/health
eureka.client.registryFetchIntervalSeconds: 30
