eureka:
  client:
    fetch-registry: false
    serviceUrl:
	defaultZone: http://localhost:8083/eureka/
spring:
   rabbitmq:
    host: 192.168.10.60
    port: 5672
    username: admin
    password: 123456
    virtual-host: bus

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"
      

