eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8083/eureka/
spring:
  rabbitmq:
    host: 192.168.10.60
    port: 5672
    username: admin
    password: 123456
    virtual-host: bus

